### ISSUE TITLE
where are the .torrent files saved? 

### ISSUE THREAD

**Issue by arielelkin** [QuantumObject/docker-transmission#5]
When we add a new torrent, where is the corresponding `.torrent` file saved? what about torrents downloaded via magnet link?

**Comment by angelrr7702** [comment]
Hi,

 Sorry for delay .. The problem with this container that the user need to choose the login and password  at the moment it create it .. and under /home/user_name  will be all the data for that user. but because I can't used variable at VOLUME I'm unable to create a way to mount a Volume directly to the where is the .torrent file save  but you can add 

-v [your_directory:]/var/backups  to docker run and them from the server execute this command to copy data from /home/[user_name]/... to /var/backups using this command .

            docker exec -it container_id /sbin/backup


there are other way to make this better .. fell free to fork this container and modified for your convenience. 

sincerely
Angel Rodriguez
